// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Pau Aliagas <linuxnow@gmail.com>

/* Golden pin for the test-only inject paths (--inject-sine / --inject-copy).
 *
 * These two are the only places reac-repacer reaches INTO a REAC frame's audio
 * region; everything else in the daemon is a byte-blind L2 relay. The bytes they
 * write are a wire fact — the channel-pair braid — so the useful property to pin
 * is not "the code looks right" but "the emitted frame is byte-for-byte what it
 * was before". That is what this test does: it drives inj_sine() and inj_copy()
 * over the WHOLE legal domain (every even channel width 2..40, every slot in
 * each width, clean and OHRCA-trailered frame lengths) and folds each resulting
 * frame — header, audio region, end marker and trailer alike, so a stray write
 * anywhere is caught — into an FNV-1a 64 digest compared against
 * inject_goldens.inc.
 *
 * The fixture was generated by this same driver run against the pre-libreac
 * implementation (the hand-written braid byte map, `./test_inject --regen`), so
 * any later refactor of those paths — the braid moving to reac_braid_pos(), the
 * geometry moving to libreac's OHRCA-aware oracles — has to reproduce the old
 * bytes exactly or the digests diverge. Regenerate ONLY when a change to the
 * emitted bytes is intended and justified; a diff in this fixture is a change to
 * what a desk receives.
 *
 * One caveat worth knowing before chasing a failure: the inject-sine digests
 * fold the output of libm's sin(), so they are pinned to the C library the
 * fixture was generated with (glibc, x86-64). The inject-copy digests are
 * integer end to end and pin the same byte map on their own — if only the sine
 * column diverges on a new toolchain, suspect libm before suspecting the braid.
 *
 * The test includes the daemon's translation unit (main renamed) because the
 * inject paths are static and driven off file-scope state — there is no header
 * to link against, and inventing one for two test-only functions would be a
 * bigger change to the relay than the thing under test.
 */

#define main repacer_main
#include "../tools/reac_repacer.c"
#undef main

#include <inttypes.h>

#include "inject_goldens.inc"

static int fails;
#define CHK(cond) do { \
	if (!(cond)) { fails++; fprintf(stderr, "FAIL %s:%d: %s\n", __FILE__, __LINE__, #cond); } \
} while (0)

/* FNV-1a 64: fold a whole frame, so a byte written outside the intended slot is
 * as visible as a byte written wrongly inside it. */
static uint64_t fnv1a(uint64_t h, const uint8_t *p, int n)
{
	for (int i = 0; i < n; i++) {
		h ^= p[i];
		h *= 0x100000001b3ULL;
	}
	return h;
}
#define FNV_INIT 0xcbf29ce484222325ULL

/* A legal REAC audio frame of `nch` channels: 50 B header (EtherType 0x8819,
 * type 0x0000 = FILLER, the only type the injectors touch), nch*36 B of audio,
 * the C2 EA end marker, and — with `trailer` — the OHRCA +2 CRC bytes an
 * M-5000/M-480 fabric appends after it. Returns the frame length on the wire.
 * The audio region is pre-filled with a non-zero pattern so an injector that
 * fails to overwrite a byte is distinguishable from one that writes zero. */
static int build_frame(uint8_t *f, int nch, int trailer)
{
	int clean = 52 + nch * 36;
	for (int i = 0; i < clean + 2; i++)
		f[i] = (uint8_t)(0x5a + i * 7);
	f[12] = 0x88; f[13] = 0x19;
	f[16] = 0x00; f[17] = 0x00;
	f[clean - 2] = 0xC2; f[clean - 1] = 0xEA;
	return trailer ? clean + 2 : clean;
}

/* Every slot of one width, one digest. The oscillator state (phase) is reset per
 * slot so the case is independent of the order slots are visited in. */
static uint64_t sine_case(int nch, int trailer)
{
	uint8_t f[2048];
	uint64_t h = FNV_INIT;
	for (int slot = 0; slot < nch; slot++) {
		int len = build_frame(f, nch, trailer);
		g_inj_slot = slot;
		g_inj_freq = 997.0;
		g_inj_amp  = 7.5e6;
		g_inj_ph   = 0.1234;
		inj_sine(f, len);
		h = fnv1a(h, f, len);
	}
	return h;
}

/* Same sweep for the copy injector. inj_copy pops from the ring the OUT-port
 * reader fills; here the ring is pre-loaded with a fixed 24-bit pattern and the
 * write pointer kept 2048 ahead of the read pointer, so every call pops 12 real
 * samples and the sequence is a pure function of how many calls came before. */
static uint64_t copy_case(int nch, int trailer)
{
	uint8_t f[2048];
	uint64_t h = FNV_INIT;
	for (int slot = 0; slot < nch; slot++) {
		int len = build_frame(f, nch, trailer);
		g_cp_dst = slot;
		__atomic_store_n(&g_cpr_w, g_cpr_r + 2048, __ATOMIC_RELEASE);
		inj_copy(f, len);
		h = fnv1a(h, f, len);
	}
	return h;
}

/* The read half of the braid — braid_read(), which inj_copy_rx drives on the
 * OUT-port frames — cannot be reached through the digests above: it lives behind
 * a blocking AF_PACKET loop, and the goldens only pin what goes ONTO the wire.
 * It is pinned instead by inversion. The write map is already golden-pinned byte
 * for byte across the whole domain, so showing that braid_read recovers exactly
 * what braid_write placed, at every width and slot and over values that exercise
 * both polarities and the bit-23 sign extension, pins the read map to the same
 * bytes. A read map that disagreed with the golden write map could not round-trip.
 */
static void roundtrip_case(int nch, int *fails_out)
{
	/* zero, both polarities at ±1, full scale either side of the sign boundary,
	 * quarter scale, and values that isolate each of the three bytes */
	static const int32_t vec[REAC_SAMPLES_PER_PKT] = {
		0, 1, -1, 0x7fffff, -0x800000, 0x400000, -0x400000,
		0x123456, -0x123456, 0x00ff00, 0x0000ff, 0x00ffff
	};
	uint8_t f[2048];

	for (int slot = 0; slot < nch; slot++) {
		(void)build_frame(f, nch, 0);
		uint8_t *a = f + REAC_AUDIO_OFFSET;
		for (int s2 = 0; s2 < REAC_SAMPLES_PER_PKT; s2++)
			braid_write(a, s2, slot, nch, vec[s2]);
		for (int s2 = 0; s2 < REAC_SAMPLES_PER_PKT; s2++) {
			int32_t got = braid_read(a, s2, slot, nch);
			if (got != vec[s2]) {
				(*fails_out)++;
				fprintf(stderr, "FAIL braid round-trip %d ch slot %d sample %d: "
				        "%" PRId32 " != %" PRId32 "\n", nch, slot, s2, got, vec[s2]);
			}
		}
	}
}

static void ring_init(void)
{
	for (unsigned i = 0; i < CPR_SZ; i++) {
		/* a spread of 24-bit signed values, both polarities, sign bit exercised */
		int32_t v = (int32_t)(i * 2654435761u) >> 8;
		g_cpr[i] = v;
	}
	g_cpr_r = 0;
	__atomic_store_n(&g_cpr_w, 4096u, __ATOMIC_RELEASE);   /* clears inj_copy's prime gate */
}

int main(int argc, char **argv)
{
	int regen = (argc > 1 && !strcmp(argv[1], "--regen"));
	int n = 0;
	uint64_t sine[64], copy[64];

	for (int nch = 2; nch <= 40; nch += 2)
		for (int trailer = 0; trailer < 2; trailer++)
			sine[n++] = sine_case(nch, trailer);

	ring_init();
	n = 0;
	for (int nch = 2; nch <= 40; nch += 2)
		for (int trailer = 0; trailer < 2; trailer++)
			copy[n++] = copy_case(nch, trailer);

	if (regen) {
		printf("/* generated by tests/test_inject.c --regen -- do not hand-edit */\n");
		printf("static const struct { int nch, trailer; uint64_t sine, copy; } INJECT_GOLDENS[] = {\n");
		n = 0;
		for (int nch = 2; nch <= 40; nch += 2)
			for (int trailer = 0; trailer < 2; trailer++, n++)
				printf("\t{ %2d, %d, 0x%016" PRIx64 "ULL, 0x%016" PRIx64 "ULL },\n",
				       nch, trailer, sine[n], copy[n]);
		printf("};\n");
		return 0;
	}

	n = 0;
	for (int nch = 2; nch <= 40; nch += 2) {
		for (int trailer = 0; trailer < 2; trailer++, n++) {
			if (INJECT_GOLDENS[n].nch != nch || INJECT_GOLDENS[n].trailer != trailer) {
				fprintf(stderr, "FAIL fixture out of order at %d\n", n);
				return 1;
			}
			if (sine[n] != INJECT_GOLDENS[n].sine) {
				fails++;
				fprintf(stderr, "FAIL inject-sine %2d ch trailer=%d: %016" PRIx64
				        " != golden %016" PRIx64 "\n",
				        nch, trailer, sine[n], INJECT_GOLDENS[n].sine);
			}
			if (copy[n] != INJECT_GOLDENS[n].copy) {
				fails++;
				fprintf(stderr, "FAIL inject-copy %2d ch trailer=%d: %016" PRIx64
				        " != golden %016" PRIx64 "\n",
				        nch, trailer, copy[n], INJECT_GOLDENS[n].copy);
			}
		}
	}

	for (int nch = 2; nch <= 40; nch += 2)
		roundtrip_case(nch, &fails);

	printf("test_inject: %d width/trailer cases (%d slot injections per injector), "
	       "%d braid round-trips, %d failures\n",
	       n, 420, 420 * REAC_SAMPLES_PER_PKT, fails);
	return fails ? 1 : 0;
}
